[ID-47]Fix nudges processes docs
rokwire/lms-building-block pull request #48
Opened 2022-08-10 10:59 UTC by stefanvit

resolved #47

2022-08-11 04:12 UTC, petyos requested changes

2022-08-11 04:12 UTC, petyos commented on CHANGELOG.md
> +- Fix nudges processes docs [#47](https://github.com/rokwire/lms-building-block/issues/47)
It should be in Fixed section.

2022-08-11 04:12 UTC, petyos commented on driver/web/docs/schemas/nudges/NudgesProcess.yaml
> +          netID:
All should follow the conventions net_id instead of netID.

2022-08-12 04:56 UTC, petyos approved these changes
LGTM

2022-08-12 04:59 UTC, petyos commented
Hi @stefanvit , could you please fix the conflicts and merge this on develop? Thanks.

2022-08-12 06:18 UTC, stefanvit commented
> Hi @stefanvit , could you please fix the conflicts and merge this on develop? Thanks.

Done

2022-08-12 06:39 UTC, petyos commented on driver/web/docs/schemas/nudges/NudgesProcess.yaml
> +  - createdAt
Should not be created_at and completed_at?

2022-08-12 06:39 UTC, petyos commented on driver/web/docs/schemas/nudges/NudgesProcess.yaml
> +  createdAt:
Should not be created_at and completed_at?

2022-08-12 11:00 UTC, merged