[ID-59]Set appID and orgID for notifications
rokwire/lms-building-block pull request #60
Opened 2022-10-18 09:03 UTC by stefanvit

## Description
Adding the enviorment variables for appID and orgID used for the NotificationBB dependances.

**Resolves #59 

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

- [x] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
Set new env variables for appID and orgID

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

2022-10-19 04:02 UTC, petyos requested changes
You have not done any changes of how the Notifications BB is called. You have added org id and app but do not use them anywhere.

2022-10-19 04:02 UTC, petyos commented on main.go
> +	ntAppID := getEnvKey("LMS_NOTIFICATIONS_APP_ID", true)
Let's name them LMS_ORG_ID and LMS_APP_ID as they are not directly related with the notifications BB but are related with the multi tenancy support.

2022-10-20 07:16 UTC, petyos requested changes

2022-10-20 07:16 UTC, petyos commented on driven/notifications/adapter.go
> +			"appID":      a.appID,
Notifications BB expects "org_id" and "app_id" format.

2022-10-20 10:52 UTC, petyos submitted a review, later dismissed
LGTM

2022-10-21 10:31 UTC, petyos submitted a review, later dismissed
LGTM

2022-11-16 07:31 UTC, petyos submitted a review, later dismissed
Please revert go.mod, test and then merge. go.mod should not be modified for this change.

2022-11-16 09:27 UTC, petyos approved these changes

2022-11-18 09:07 UTC, mdryankov approved these changes

2022-11-18 09:08 UTC, merged